### ISSUE TITLE
Crash when Starting a New Game

### ISSUE THREAD

**Issue by bernardb13** [LibreVR/RoboRevive#12]
I have had wonderful success running RR using RoboRevive.  I have found something odd though:

If I click on an empty game slot and start a New Game, I go through the intro and make it to the Office and then shortly thereafter the game always crashes either while still in either the office or in the first minute or two of the first scenario (mission).

Fortunately I have a saved game position which is past that point so I can still play when I Continue from that game slot.

**Comment by Armada651** [comment]
Are you using Windows 7?

**Comment by bernardb13** [comment]
Thanks for the response.

I am running Windows 10.  I don't want to waste any more of your time.  My crashes are very unpredictable so I have a feeling there is some process or background application running on my computer causing the Unreal Engine to crash.

I am still trying to track it down by quitting different processes and seeing what happens.

Thanks for your awesome work on this project!

**Comment by bernardb13** [comment]
Have been playing hard and no crashes at all.  I don't know what could have been running in the background on my computer to cause the crashes, but by disabling various startup processes seems to have eliminated any crashing issues for me.  I have 100% success now, all missions, new games, old games...all working perfectly.  Thanks again for your work on this Armada651!

**Comment by Armada651** [comment]
Did you update RoboRevive before you tested? Because I did make some low-level changes in 1.0 that could have fixed the crashes. I think the switch to the MinHook library may have fixed this issue.

In any case, I'm closing this one as fixed.
