### ISSUE TITLE
Menu button?

### ISSUE THREAD

**Issue by AzraelXS** [LibreVR/RoboRevive#15]
There doesn't seem to be a button bound to the Robo Recall in-game menu. In order to change settings or exit the game, I have to take off my headset, close the game, and relaunch it. A bit annoying, but wow does this mod run smoother than with "actual" Revive. Thank you so much for your efforts!

**Comment by KilianZ** [comment]
When you open the SteamVR overlay the game pauses and when you close it again you can access the in-game menu. Though I agree we should be able to do this with the actual menu button since it doesn't have anything bound to it yet.

**Comment by Armada651** [comment]
Fixed in commit a39b208d54a54f83617ccacd0bc48829a88ba43c. Will be part of the next release.
