### ISSUE TITLE
Headset Error after installer fails to "prompt you to install the RoboRevive mod"

### ISSUE THREAD

**Issue by TSMMark** [LibreVR/RoboRevive#23]
The readme says 

> At the end of the installation, Robo Recall will prompt you to install the RoboRevive mod.

This does not happen for me when the installer finishes. It looks like it tries to launch something, then the oculus app restarts.

Now, the Robo Recall shortcut on my desktop is not linked, but if I navigate to the Robo Recall install dir and launch `bin/RoboRecall-Win64-Shipping.exe` I get the

> Headset Error 
> You have a pending hardware issue that is preventing you from entering VR. Please check that your headset and sensor are connected.

**Comment by TSMMark** [comment]
Fixed, apparently I was installing RoboRevive in a location other than the install directory of the Robo Recall game. Cheers

**Comment by thesmoovb** [comment]
I'm having the same issue, but can't figure out how my install directory could be wrong. 
E:\Software\epic-games-odin\RoboRecall\Plugins\Revive
