### ISSUE TITLE
"failed to launch epic-games-odin" - Robo Recall launches OK on first attempt, fails after game has been quit once.

### ISSUE THREAD

**Issue by djwhatle** [LibreVR/RoboRevive#24]
Windows 10 Creators Update + HTC Vive + SteamVR (stable) + Revive + RoboRevive + OpenVR Advanced Settings

After a fresh Windows 10 boot I'm able to launch and play the game, but after exiting and attempting to launch again I get a simple error "failed to launch epic-games-odin" with no additional detail available.

Not sure if this has anything to do with it, but I did modify the reprojection settings from "reproject + async" to "_no_ reprojection" while playing the game through the OpenVR Advanced Settings menu (in headset).

Have been able to reproduce this twice now.  Should I not have Revive and RoboRevive installed at the same time?

I have tried quitting through the SteamVR overlay and through the in-game menus. No effect.

**Comment by Armada651** [comment]
> Revive + RoboRevive

You can have them installed at the same time, but you can't use them at the same time. If you start through Revive Robo Recall will use the Oculus support, if you start Robo Recall normally it will use RoboRevive.

**Comment by djwhatle** [comment]
Below is a list of everything Vive related installed on my machine.

> Windows 10 Creators Update + HTC Vive + SteamVR (stable) + Revive + RoboRevive + OpenVR Advanced Settings

I am launching the game through the "Steam" option of the SteamVR menu (in-headset menu). Not launching the game through the "Revive" option.

**Comment by Armada651** [comment]
Try the Robo Recall desktop shortcut.

**Comment by djwhatle** [comment]
Still troubleshooting, but on first attempt I booted up Windows, immediately clicked the Robo Recall desktop shortcut (Steam had not yet launched) and Oculus Home launched along with SteamVR.

Oculus Home complained about not detecting my headset, SteamVR said my headset was detected and the light turned green, but the screen never came on (attempted headset reboot, no dice).

Now rebooting Windows again, will click desktop shortcut after starting SteamVR.

**Comment by djwhatle** [comment]
This time started up Windows, launched SteamVR, clicked desktop shortcut, and then was able to launch game this way 4 times so far. 

Does the desktop shortcut use Revive or RoboRevive?

**Comment by djwhatle** [comment]
I added a non-steam-game shortcut to the desktop shortcut and now I'm able to launch from the "Steam" menu in-headset successfully.

**Comment by Armada651** [comment]
Desktop shortcut start RoboRecall normally, which uses the RoboRevive mod if you have it installed.
