### ISSUE TITLE
Issue replacing plugin with mod

### ISSUE THREAD

**Issue by Parawalky** [LibreVR/RoboRevive#27]
When I run the installer I get the error message "Cannot replace default plugin with a mod" error at the end. Apologies if this is an easy fix, I'm not all that computer savvy. Thanks.

**Comment by Armada651** [comment]
What's the contents of your `C:\Program Files\Oculus\Software\Software\epic-games-odin\RoboRecall\Plugins` directory? (Depending on where you installed your Oculus Library)

**Comment by Parawalky** [comment]
These guys:
RoboRecall-Win64-Shipping.modules 
RoboRecall-NativizedAssets-Win64-Shipping.dll

**Comment by Armada651** [comment]
Strange, try putting these files in the Plugins folder manually: 
[Revive.zip](https://github.com/LibreVR/RoboRevive/files/1005817/Revive.zip).

**Comment by Parawalky** [comment]
Odd, error messages stopped and it's running great now. Thanks!
