### ISSUE TITLE
Crashing since update

### ISSUE THREAD

**Issue by GKN138** [LibreVR/RoboRevive#34]
Robo Recall was updated earlier today, and Robo Revive hasn't been working for me since.  Started fine last night. Tonight when I tried to start it, I got "An Unreal process has crashed: UE4-RoboRecall".

Had the following message:

LoginId:79f9e17441793aaac434a38d46f0bd05
EpicAccountId:

You do not have any debugging symbols required to display the callstack for this crash.
[UE4CC-Windows-30E0DD4D4B71E4211E0F2593B1967394_0000.zip](https://github.com/LibreVR/RoboRevive/files/1529335/UE4CC-Windows-30E0DD4D4B71E4211E0F2593B1967394_0000.zip)

Attached zip file is the log directory I was pointed to by the crash report.

Thanks.

**Comment by Armada651** [comment]
I'm no longer developing RoboRevive, while I like the project on a technical level, it makes more sense for me to further improve Revive instead. So I recommend you use regular Revive to start Robo Recall now.

**Comment by GKN138** [comment]
Understood, thanks for the update.
