### ISSUE TITLE
not working anymore since Robo Recall V1.5

### ISSUE THREAD

**Issue by strueli** [LibreVR/RoboRevive#35]
Robo Recall did an (automatic) update today to V1.5, and now it seems to be not working anymore.
It won't start up, but gets the 'unreal engine crashed' message

**Comment by duckula99** [comment]
Confirmed,  I am also receiving the crash
Also destroyed revive functionality.  Injection does not fail but fails to detect controllers.
Let me know if I can help.

**Comment by Toony77** [comment]
Avoid updating 1.5 in the meantime, for me it's too late it's done so error message for me too xD

**Comment by mjanek20** [comment]
Yeah :( Can you please please please fix that ? I love this game ...

**Comment by Armada651** [comment]
You should switch to regular Revive, I won't be developing RoboRevive anymore.

**Comment by mjanek20** [comment]
This is horrible news. RoboRevive works with 2.0 SS and Revive version barely keeps 1.2. It's soooo much worse not being a native app anymore.

**Comment by mjanek20** [comment]
I've a developer myself but I've never debugged Unreal Engine. How hard would it be to patch it ?

**Comment by Armada651** [comment]
@mjanek20 Have you tried the latest Revive beta version?

**Comment by mjanek20** [comment]
Yes, I've just went out of VR. The performance is soooo much worse :( I'm sorry for being a little bugger but it would be a huge shame if we could not be using native support.

**Comment by Armada651** [comment]
This may be caused by adaptive quality isn't implemented in Revive yet. Robo Recall could be adjusting quality down for you when using 2.0 SS.

**Comment by mjanek20** [comment]
There's a switch in the options to enable or disable adaptive quality. I'm sure that what I was seeing before it crushing was 2.0 SS and nothing less.

**Comment by Armada651** [comment]
In that case I'd rather focus on improving Revive performance. The RoboRevive code is difficult to maintain and has known crashing issues even before the V1.5 update.

You're free to take over if you want, I'd be glad to help you getting it to compile again if you're willing to maintain it.

**Comment by Meteoryte** [comment]
Any way to fix the deadzone issues in Robo Recall without this? I have a nolo and the deadzone is an issue for me anc can't teleport in all directions...

**Comment by Armada651** [comment]
You can reduce the deadzone using OpenVR-AdvancedSettings.

**Comment by Meteoryte** [comment]
Tried that, it doesn't actually seem to do anything.

**Comment by Armada651** [comment]
The beta currently doesn't support reloading the settings on-the-fly, you need to change the settings *before* you start the game.

**Comment by Meteoryte** [comment]
Hmm I'll try this. Thanks.

**Comment by AirRaidMaterial** [comment]
This makes me sad as well. I have no idea how to get Robo Recall to run smooth with Revive, as it did with Robo Revive.

I don't know what to do : (

**Comment by Toony77** [comment]
Roborevive no longer works unfortunately, you have to go through revive but at home it crash ... I just hope that the new version of revive will work correctly robo recall ...

**Comment by Armada651** [comment]
This new release should fix it: https://github.com/LibreVR/RoboRevive/releases/tag/v1.1

**Comment by Meteoryte** [comment]
Thanks!

**Comment by Toony77** [comment]
Thanks, he's working on WMR  :)
