### ISSUE TITLE
White Screen when loading a level from the Mod menu.

### ISSUE THREAD

**Issue by kusokuso1** [LibreVR/RoboRevive#4]
<I apologize in advance if this is the wrong place to post this, as it may not be an issue with RoboRevive>
I have not purchased the game.  
I installed UE4 and downloaded the Robo Recall mod.
Unzipped the repository https://github.com/LibreVR/RoboRevive/archive/master.zip and placed it in the appropriate folder.

Home Hub area runs perfect on Vive (shooting range too).  However, when I go to the blue marker in there and try to launch a mission from the mods menu, the game gets stuck.  

The game window on the desktop shows a white screen. On the Vive it shows an empty level, with Vive controllers, sensors and a black window with a loading-like icon is animating.  No errors are displayed.

Perhaps I should post this on the UE4 site? Any instructions would be extremely appreciated.

**Comment by vicvr** [comment]
The very first mission works, you might have to wait a bit more for it to load. Seems you can't proceed past it though.

**Comment by kusokuso1** [comment]
@vicvr 
thanks a lot for the confirmation.  I read somewhere else that the first "level" works, and thought that meant the hub (the office area w/ the shooting range).  

Just found out that most, if not all the levels in Mod List dropdown are the actual official levels, not modded ones.  Just tried level 1 Batch Recall and it played no problem.  Sorry about wasting your time. I'll close this out.  Thanks again!

**Comment by kusokuso1** [comment]
@vicvr
thanks a lot for the confirmation. I read somewhere else that the first "level" works, and thought that meant the hub (the office area w/ the shooting range).

Just found out that most, if not all the levels in Mod List dropdown are the actual official levels, not modded ones. Just tried level 1 Batch Recall and it played no problem. Sorry about wasting your time. I'll close this out. Thanks again!
