### ISSUE TITLE
"Mods" button doesn't show up, am I doing something wrong?

### ISSUE THREAD

**Issue by xnurt** [LibreVR/RoboRevive#6]
I realize this isn't an issue with this mod, but either me or the game.. but I install the mod, and it says to choose "mods" in the roborecall main menu to play it... but I swear I don't see it. Am I blind?

**Comment by vicvr** [comment]
It's inside the home hub. Go to the gun range / mission selection screen inside the apartment and you'll see it on top.

**Comment by Armada651** [comment]
For version 0.2 you don't need to activate the mod.
