### ISSUE TITLE
Grip Toggle

### ISSUE THREAD

**Issue by vicvr** [LibreVR/RoboRevive#7]
Ok, so I've been dabbling with this a bit more and I have a working Grip Toggle functionality. Two problems though:

1. Again I had to modify base game assets: \RoboRecallModKit\RoboRecall\Content\Character\Player\Avatars\BP_DefaultHand.uasset > Manage Grip State
2. Are blueprints not translated to readable code anywhere? Very difficult to understand what goes where and they don't seem to be version-control-friendly, so collaboration might become a huge pain

My blueprint changes, if anyone wants to take a look:

![grip_toggle](https://cloud.githubusercontent.com/assets/26304576/23803142/e4321f6c-05b5-11e7-8f23-0f37d87fba43.png)

I'll be adding Hybrid grip support as well, in the meantime how the heck do I package this so it's usable by others without modifying core files?

**Comment by vicvr** [comment]
Haven't had time to share this yet, but here's my implementation for the hybrid grip functionality, if anyone wants to reuse it. I'll open another issue to share my current changes.

![hybrid-grip-1](https://cloud.githubusercontent.com/assets/26304576/23833848/2c265986-074c-11e7-8948-9d07e81e61a8.png)
![hybrid-grip-2a](https://cloud.githubusercontent.com/assets/26304576/23833847/2c259be0-074c-11e7-838e-04f1e318c3ca.png)
![hybrid-grip-3](https://cloud.githubusercontent.com/assets/26304576/23833849/2c26f2ec-074c-11e7-8b64-fdcbf3e2a982.png)

**Comment by Armada651** [comment]
I'm going to look at this issue next. Again, we can't override `BP_DefaultHand` without affecting the VR pawn which is not an option as explained earlier.

However, we may be able to override gripping behavior for our custom weapons. This is also preferable to just having Toggle Grip on everything.

In any case, I'll be sure to take into account your work here, it should prove useful.

**Comment by Armada651** [comment]
There doesn't seem any way to implement this without touching `BP_DefaultHand`. I think I'll just implement a Hybrid Grab like Revive in the SteamVR plugin itself.

**Comment by Armada651** [comment]
Hybrid grip support is implemented in commit 8821373951bfa2e3e804d78ff1e72f71ab386076.
